spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    h2:
      url: jdbc:h2:mem:test
      username: sa
      password:
      driverClassName: org.h2.Driver
    mariadb:
      url: jdbc:mariadb://localhost:3306/travel
      username: root
      password: 1q!1q!
      driverClassName: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  logging:
    level:
      root: INFO
    file:
      name: logs/myapp.log
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %class{50}.%M:%line - %msg%n"
      file: "%date{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50}:%line - %msg%n"
    org:
      springframework : DEBUG
      hibernate:
        SQL: DEBUG
        type: descriptor.sql.BasicBinder=TRACE

cloud:
  aws:
    credentials:
      accessKey: test
      secretKey: test
    s3:
      bucket: relink
      url: https://s3.ap-northeast-2.amazonaws.com/relink
    region:
      static: ap-northeast-2
    stack:
      auto: false
